services:
  db: # DBã®è¨­å®š(PostgreSQL)
    image: postgres:15-alpine
    container_name: salon-db
    env_file: .env  
    environment:
      # POSTGRES_USER ãªã©ã€ç‰¹å®šã®åå‰ãŒå¿…è¦ãªã‚‚ã®ã ã‘ãƒãƒƒãƒ”ãƒ³ã‚°
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"] # ãƒ‡ãƒ¼ã‚¿ãƒ™ãƒ¼ã‚¹ãŒæº–å‚™OKã‹ç¢ºèªã™ã‚‹ã‚³ãƒãƒ³ãƒ‰
      interval: 5s   # 5ç§’ãŠãã«ãƒã‚§ãƒƒã‚¯
      timeout: 5s    # 5ç§’ã§ã‚¿ã‚¤ãƒ ã‚¢ã‚¦ãƒˆ
      retries: 5     # 5å›å¤±æ•—ã—ãŸã‚‰ãƒ€ãƒ¡ã¨ã¿ãªã™
      start_period: 60s # èµ·å‹•ç›´å¾Œã®10ç§’é–“ã¯å¤±æ•—ã—ã¦ã‚‚å¤§ç›®ã«è¦‹ã‚‹

  backend:
    build: # goã®è¨­å®š
      context: ./backend
      dockerfile: Dockerfile
    container_name: salon-backend
    env_file: .env  
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db   # ã“ã“ã ã‘ã¯ã‚µãƒ¼ãƒ“ã‚¹åå›ºå®š
    volumes:
      - ./backend:/backend
    working_dir: /backend
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      # ãƒãƒƒã‚¯ã‚¨ãƒ³ãƒ‰ãŒ8080ãƒãƒ¼ãƒˆã§å¾…ã¡å—ã‘ã‚’é–‹å§‹ã—ãŸã‹ãƒã‚§ãƒƒã‚¯
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s # ãƒ“ãƒ«ãƒ‰ã«æ™‚é–“ãŒã‹ã‹ã‚‹ã®ã§é•·ã‚ã«è¨­å®š
  
  frontend:
      build: ./frontend
      container_name: salon-frontend
      ports:
        - "3000:3000"
      volumes:
        - ./frontend:/app
        - /app/node_modules # ãƒ©ã‚ºãƒ‘ã‚¤ã¨PCã§node_modulesãŒç«¶åˆã—ãªã„ã‚ˆã†ã«
      command: npm run dev
      environment:
        - NEXT_PUBLIC_API_URL=http://localhost:8080
        - NODE_OPTIONS=--max-old-space-size=1024 # ğŸ’¡ 2GBã¾ã§è¨±å¯ã™ã‚‹
        - WATCHPACK_POLLING=true
        - CHOKIDAR_USEPOLLING=true # ã“ã‚Œã‚’è¿½åŠ ï¼ˆå¤ã„æ¤œçŸ¥æ–¹å¼ã‚‚ã‚«ãƒãƒ¼ï¼‰
      depends_on:
        backend:
          condition: service_healthy